version: '3.9'

services:
  backend:
    image: aniket52kr/smartrecruit-backend:latest
    container_name: smartrecruit-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    ports:
      - "3000:3000"
    networks:
      - smartrecruit-network


  frontend: 
    image: aniket52kr/smartrecruit-frontend:latest
    container_name: smartrecruit-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - smartrecruit-network


networks:
  smartrecruit-network:
    driver: bridge 